# Site settings
name: Timeline
title: Dan Li
email: danli2004@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dan Li's personal Web site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danliIDEA.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  danliIDEA

# Build settings

markdown: kramdown
highlighter: rogue
